
import { Geist, Geist_Mono, Anta } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";
import Header from "../components/Header";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anta = Anta({
  variable: "--font-anta",
  subsets: ["latin"],
  weight: "400"
});

// To set dark mode


// export const metadata = {
//   title: "Prajwal Rangegowda",
//   description: "Generated by create next app",

//   manifest: "/manifest.json",
  

// };

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#000000" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="Prajwal Rangegowda" />
        <meta name="mobile-web-app-capable" content="yes" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/icons/icon-48x48.png" />
        <title>Prajwal Rangegowda</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
