import { Geist, Geist_Mono, Anta } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import Image from "next/image";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anta = Anta({
  variable: "--font-anta",
  subsets: ["latin"],
  weight: "400"
});

export const metadata = {
  title: "PrajwalRangegowda",
  description: "Generated by create next app",
  icons: { icon: "/favicon.ico?v=2" }
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.layout}>
          <header className={`${styles.header }`}>
            <div className={styles.siteLogo}>
              <Link href={"/"}>
            <Image
              className={`${styles.logo} ${styles.logoDark}`}
              src="/prajwal-logo-dark.png"
              alt="Prajwal logomark"
              width={30}
              height={30}
            />
            <Image
              className={`${styles.logo} ${styles.logoLight}`}
              src="/prajwal-logo-light.png"
              alt="Prajwal logomark"
              width={30}
              height={30}
            />
              </Link>
            <Link className={styles.sitetitle} href={"/"}>Prajwal Rangegowda</Link>
            </div>
            <nav className={styles.nav}>
              <ul> 
                <li>
                  <a href="/design">Design</a>
                </li>
                <li>
                  <a href="/about">About</a>
                </li>
                <li>
                  <a href="https://blog.prajwalrangegowda.com">Blog</a>
                </li>
              </ul>
            </nav>
          </header>
        </div>
        {children}
      </body>
    </html>
  );
}
